import React from "react";
import { TableBlock } from "../components/runtime/TableBlock";

const Elementcentre: React.FC = () => {
  return (
    <div id="page-elementcentre-2">
    <div id="ipv1tx" style={{"display": "flex", "height": "100vh", "fontFamily": "Arial, sans-serif", "--chart-color-palette": "default"}}>
      <nav id="ih0ix4" style={{"width": "250px", "background": "linear-gradient(135deg, #4b3c82 0%, #5a3d91 100%)", "color": "white", "padding": "20px", "overflowY": "auto", "display": "flex", "flexDirection": "column", "--chart-color-palette": "default"}}>
        <h2 id="i07605" style={{"marginTop": "0", "fontSize": "24px", "marginBottom": "30px", "fontWeight": "bold", "--chart-color-palette": "default"}}>{"BESSER"}</h2>
        <div id="iozkig" style={{"display": "flex", "flexDirection": "column", "flex": "1", "--chart-color-palette": "default"}}>
          <a id="ir5bda" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/centrecongres">{"CentreCongres"}</a>
          <a id="iq7fd6" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/gestionnaire">{"Gestionnaire"}</a>
          <a id="i6wozm" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "rgba(255,255,255,0.2)", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/elementcentre">{"ElementCentre"}</a>
          <a id="i3ig8q" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/reservation">{"Reservation"}</a>
          <a id="ijhs4t" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/periodeindisponibilite">{"PeriodeIndisponibilite"}</a>
          <a id="iut14c" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/evenement">{"Evenement"}</a>
          <a id="i9k4mh" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/salle">{"Salle"}</a>
          <a id="ikzbai" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/materiel">{"Materiel"}</a>
          <a id="i5x68f" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/prestation">{"Prestation"}</a>
        </div>
        <p id="iaaqe8" style={{"marginTop": "auto", "paddingTop": "20px", "borderTop": "1px solid rgba(255,255,255,0.2)", "fontSize": "11px", "opacity": "0.8", "textAlign": "center", "--chart-color-palette": "default"}}>{"© 2026 BESSER. All rights reserved."}</p>
      </nav>
      <main id="imsd3h" style={{"flex": "1", "padding": "40px", "overflowY": "auto", "background": "#f5f5f5", "--chart-color-palette": "default"}}>
        <h1 id="i3j4rp" style={{"marginTop": "0", "color": "#333", "fontSize": "32px", "marginBottom": "10px", "--chart-color-palette": "default"}}>{"ElementCentre"}</h1>
        <p id="ijt8rn" style={{"color": "#666", "marginBottom": "30px", "--chart-color-palette": "default"}}>{"Manage ElementCentre data"}</p>
        <TableBlock id="table-elementcentre-2" styles={{"width": "100%", "minHeight": "400px", "--chart-color-palette": "default"}} title="ElementCentre List" options={{"showHeader": true, "stripedRows": false, "showPagination": true, "rowsPerPage": 5, "actionButtons": true, "columns": [{"label": "Nom", "column_type": "field", "field": "nom", "type": "str", "required": true}, {"label": "Description", "column_type": "field", "field": "description", "type": "str", "required": true}, {"label": "Type", "column_type": "field", "field": "type", "type": "enum", "options": ["AMPHI", "AUTRE", "RESTAURATION", "SALLE_CONF"], "required": true}, {"label": "DureeMinLocation", "column_type": "field", "field": "dureeMinLocation", "type": "int", "required": true}, {"label": "JoursDisponibles", "column_type": "field", "field": "joursDisponibles", "type": "str", "required": true}, {"label": "Saison", "column_type": "field", "field": "Saison", "type": "enum", "options": ["BASSE", "HAUTE", "MOYENNE"], "required": true}, {"label": "Prix", "column_type": "field", "field": "Prix", "type": "float", "required": true}], "formColumns": [{"column_type": "field", "field": "nom", "label": "nom", "type": "str", "required": true, "defaultValue": null}, {"column_type": "field", "field": "description", "label": "description", "type": "str", "required": true, "defaultValue": null}, {"column_type": "field", "field": "type", "label": "type", "type": "enum", "required": true, "defaultValue": null, "options": ["AMPHI", "AUTRE", "RESTAURATION", "SALLE_CONF"]}, {"column_type": "field", "field": "dureeMinLocation", "label": "dureeMinLocation", "type": "int", "required": true, "defaultValue": null}, {"column_type": "field", "field": "joursDisponibles", "label": "joursDisponibles", "type": "str", "required": true, "defaultValue": null}, {"column_type": "field", "field": "Saison", "label": "Saison", "type": "enum", "required": true, "defaultValue": null, "options": ["BASSE", "HAUTE", "MOYENNE"]}, {"column_type": "field", "field": "Prix", "label": "Prix", "type": "float", "required": true, "defaultValue": null}, {"column_type": "lookup", "path": "centrecongres", "field": "centrecongres", "lookup_field": "nom", "entity": "CentreCongres", "type": "str", "required": true}, {"column_type": "lookup", "path": "reservation_1", "field": "reservation_1", "lookup_field": "dateDebut", "entity": "Reservation", "type": "list", "required": false}, {"column_type": "lookup", "path": "periodeindisponibilite", "field": "periodeindisponibilite", "lookup_field": "dateDebut", "entity": "PeriodeIndisponibilite", "type": "list", "required": false}]}} dataBinding={{"entity": "ElementCentre", "endpoint": "/elementcentre/"}} />
      </main>
    </div>    </div>
  );
};

export default Elementcentre;
